// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

// We use OpenZeppelin for the NFT standard
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

// Interface for the ZK Verifier (Generated by Halo2)
interface IVerifier {
    function verifyProof(
        bytes calldata proof, 
        uint256[] calldata pubSignals
    ) external view returns (bool);
}

contract OmniIdentity is ERC721 {
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIds;

    IVerifier public immutable verifier;
    
    // 1A: STRICT NULLIFIERS (Sybil Resistance)
    // Maps a NullifierHash -> The last timestamp they successfully proved.
    mapping(uint256 => uint256) public lastProofTimestamp;
    
    // 3A: SOULBOUND (Non-Transferable)
    // If true, the token cannot be moved.
    mapping(uint256 => bool) private _soulbound;

    event IdentityVerified(address indexed user, uint256 indexed tokenId);

    constructor(address _verifierAddress) ERC721("Omni Verified Human", "OMNI") {
        verifier = IVerifier(_verifierAddress);
    }

    /**
     * @dev The Main Entry Point.
     * @param proof The cryptographic proof bytes from the frontend (WASM).
     * @param nullifierHash The unique ID generated from (UserSecret + Date).
     */
    function verifyAndMint(
        bytes calldata proof,
        uint256 nullifierHash
    ) external {
        // --- CHECK 1: SYBIL RESISTANCE (1A) ---
        require(
            block.timestamp - lastProofTimestamp[nullifierHash] > 1 days,
            "Cooldown Active: You can only verify once every 24 hours."
        );

        // --- CHECK 2: ZK VERIFICATION (2A - Privacy) ---
        // We construct the Public Inputs. 
        // Note: We DO NOT send Location/Time. Only the Nullifier is public.
        uint256[] memory pubSignals = new uint256[](1);
        pubSignals[0] = nullifierHash;

        // Call the ZK Verifier
        bool isValid = verifier.verifyProof(proof, pubSignals);
        require(isValid, "Invalid ZK Proof: You are not who you say you are.");

        // --- ACTION: UPDATE STATE ---
        lastProofTimestamp[nullifierHash] = block.timestamp;

        // --- REWARD: MINT SBT (3A) ---
        _mintSBT(msg.sender);
    }

    function _mintSBT(address to) internal {
        _tokenIds.increment();
        uint256 newItemId = _tokenIds.current();
        
        _safeMint(to, newItemId);
        _soulbound[newItemId] = true;
        
        emit IdentityVerified(to, newItemId);
    }

    // --- SOULBOUND LOGIC (Prevent Transfers) ---
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 tokenId,
        uint256 batchSize
    ) internal override {
        // Allow minting (from 0x0) and burning (to 0x0), but BLOCK transfers between users.
        require(from == address(0) || to == address(0), "Err: This token is Soulbound and cannot be transferred.");
        super._beforeTokenTransfer(from, to, tokenId, batchSize);
    }
}